name: Deploy GeoServer
on:
    push:
        tags:
            - '*'
jobs:
  deploy-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Deploy GeoServer
        run: |
          cd src
          mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml deploy -P wps -DskipTests
        env:
          USER_NAME: ${{ secrets.MVN_USER }}
          ACCESS_TOKEN: ${{ secrets.MVN_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: ${{ github.ref_name }}
            name: Release ${{ github.ref_name }}
            draft: false
            prerelease: false
            files: |
                src/web/app/target/geoserver.war
            generate_release_notes: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
